version: '3'
services:
  backend-app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: transoly-docker-2
    container_name: transoly_app_container
    ports:
      - '3000:3000'
    environment:
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
  db:
    image: postgres:14.8
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: transoly_db_container
    volumes:
      - ./postgres:/var/lib/postgresql/data
