version: '3'

services:
  db:
    image: postgres:14.9
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: transoly_db_container
    volumes:
      - ./postgres:/var/lib/postgresql/data
